### ISSUE TITLE
How do I leverage hooks and custom local config from a role

### ISSUE THREAD

**Issue by khomco** [debops/ansible-dovecot#15]
I am attempting to develop a role that depends on this one and others.  I have some custom configuration that i was going to apply and wanted to do without having to modify this codebase.

How would I set the 'dovecot_custom_localconf' variable from a rendered template?

I attempted to leverage the Pre Hook, however that also seems unmanageable.  Is the use of the Pre and Post Hooks ideally used/configured from a playbook level, consuming this role, rather than a role itself?

**Comment by drybjed** [comment]
Two questions - do you care about idempotency, and what would you like/need to configure from a separate role in dovecot?

Keeping idempotency between roles without an external source of data is hard. For example, `debops.postfix` role can be run either on its own, or from a different role as a role dependency, with that second role, for example `debops.dovecot`, passing some variables to `debops.postfix` using role dependency variables, to change its configuration. But then you want to run `debops.postfix` by itself again, and guess what - those configuration variables from `debops.dovecot` are not there, so `debops.postfix` reverts the configuration back.

The way around this is to use an external source of configuration. Within normal Ansible runs, inventory is a good place to do it - you set variables there once and they are available on each run. But it's more tricky between the roles themselves. With `debops.postfix`, I came up with a system that stores the configuration that is passed from other roles in `ansible_local.postfix` dictionary, which then is read by `debops.postfix` on each run and keeps the configuration idempotent.

I don't think that `debops.dovecot` is set up with something like that - in other words it's not really written to be used as a role dependency for other roles. And with configuration this complex I'm not sure if it could be done in a reliable way... But we could figure something out. So, what do you have in mind?

**Comment by drybjed** [comment]
Ah, forgot. `dovecot_custom_localconf` is designed to get the configuration from inventory, for above reasons. Pre and post hooks won't really help you in this case either, they are designed for injecting tasks, not configuration.

**Comment by khomco** [comment]
I am developing role to install [Modoboa](http://modoboa.org/en/).  Idempotency would be of great value of course.  I wasn't aware of the ```ansible_local.postfix``` dictionary in the other roles.

A full fledged install of Modoboa would have dependencies on ```debops.secret```, ```debops.pki```, ```debops.mysql```, ```debops.postfix```, and ```debops.dovecot```.

I initially had pulled down ```debops.postfix``` and ```debops.dovecot``` and made the necessary changes to fill the gaps.  However, I had seen you have made recent improvements to ```debops.dovecot``` that in fact solved those gaps and I started to migrate to that solution.  With the remaining gaps, I figured I would try and use your existing mechanisms to inject custom configuration, however it is proving to not feel like an Ansible Role (then again I am no expert yet).

**Comment by drybjed** [comment]
You can see how the variables are passed in [debops.mailman](https://github.com/debops/ansible-mailman/blob/master/meta/main.yml) and [debops.smstools](https://github.com/debops/ansible-smstools/blob/master/meta/main.yml). The solution isn't fully complete yet, I don't have a good solution to configure `smtpd_*_restrictions` in Postfix yet.

You should switch to `debops.mariadb` role from `debops.mysql`, the latter one is deprecated and will be dropped at some point.

Good idea on using `debops.postfix` as a dependency from a virtual mail role, I planned its use that way, hence the local fact solution for configuration.

I imagine that you need to basically setup the database access in Dovecot, and the rest could be left to the role's on devices? I imagine database configuration could be exposed by a system similar to what I done in `debops.postfix`. The dovecot role was written by @ganto so I wonder what are his thoughts on this.

**Comment by drybjed** [comment]
I'm looking at Modoboa [Dovecot configuration](https://modoboa.readthedocs.org/en/latest/integration/imap_and_smtp.html) and it doesn't look promising. :-) Can you be more specific about what things you need to configure? I'm not sure if everything could be sanely translated through role dependencies, perhaps some of the configuration would need to be passed through inventory, ie. requiring manual configuration by the admin.

**Comment by khomco** [comment]
Just as I have seen in your roles, I would provide a kind of default install.  I have successfully configured the Dovecot configuration with your roles and some changes to include additional rendering of templates to meet the requirements of Modoboa.  As far as a question of doing it sanely, I could agree with that.  :)  

What I want to configure would be those things defined at [Dovecot Configuration](https://modoboa.readthedocs.org/en/latest/integration/imap_and_smtp.html) and some additional modifications that I have gathered from the only 2 blogs I could find that walk through a full install (http://gargamel.nu/my-mail-server-setup/, http://www.ollegustafsson.com/en/ultimate-mailserver-setup/).  

Both of which are a bit outdated and I walked through them manually numerous times only to end up with a non-working solution... which is why I am here ... Go Ansible!!

**Comment by khomco** [comment]
I'll work to get my current solution out on github, so I can start getting input and provide a better demonstration of what I am trying to accomplish.

**Comment by khomco** [comment]
Here it is: https://github.com/khomco/homco-modoboa.  It currently breaks at my post hook task for dovecot. It looks like my use of the template_src lookup fails since it is in the dovecot context .... ?  I am sure I could solve by modifying the .debops.cfg template-paths.

**Comment by khomco** [comment]
You'll see that it includes an older version of the ```debops.postfix``` that I modified.  I intend to look at using your newest and removing this... just haven't gotten to it yet.

**Comment by drybjed** [comment]
@khomco Ah, I see what you mean. The files in `tasks/dovecot/` won't ever be executed by Ansible, at least not without any `task_src` lookups. Still, `pre_main.yml` and `post_main.yml` files in the roles are meant to be just stub files so that Ansible won't complain about missing files if `task_src` configuration is not present, because it needs to return "something". Anyway, the way you try to add dovecot tasks won't work.

So I suppose that we will need to devise some way to point Dovecot to custom account information and make that accessible from other roles. I wonder, does Dovecot support multiple SQL databases (for example), or it only can handle one database type at a time?

For now I suggest that you finish part of the configuration through Ansible inventory and explain in the readme what is needed to be set up by the user so that role can work.

You don't need to use `debops.pki` role if you are planning to use your role within DebOps environment. It is part of the common playbook and should set up anything Dovecot and other services need beforehand.

**Comment by khomco** [comment]
I am only becoming more savvy about Dovecot and Postfix during this very effort to build this role, so I don't know if Dovecot supports multiple SQL databases.

Thanks for the advice on ```debops.pki```. It took me a moment to realize what you meant, but I understand.  I have not yet established 'my environment' with DebOps, but have every intention of using the common playbook.

Are you suggesting I develop this Role with the intent to only make changes related to the needs of Modoboa and assume Dovecot (any others?) are already installed and configured on the server (possibly perform some checks)?

**Comment by drybjed** [comment]
Basically, yes. You can do this in two ways right now:

- either assume that Dovecot is set up by the user and explain what's needed in the readme, and just configure Modoboa and Postfix via role dependency variables;

- or create separate playbook in which you run `debops.dovecot` with your own configuration passed via role variables, and your Modoboa role. It won't be idempotent outside of that playbook (ie. when you run `debops.dovecot` itself later, configs will be overwritten) but you will be able to setup Modoboa as you see fit yourself.

Also if you plan to use DebOps main playbook, I invite you to come to `#debops` IRC channel on FreeNode. :-)

**Comment by khomco** [comment]
Thank you for the invite and your support in answering my questions.

**Comment by ganto** [comment]
Even the issue is already closed, I still drop a few comments, as I'm the main author of the dovecot role. 

First of all, I'm sorry, that it took me so long to rework the role to support LMTP. I quickly checked the Dovecot configuration requirements of Modoboa and that probably would have been even easier to write a separate role than to include all the required changes in the old version here.

I think with the new configuration layout it looks a bit better, but as drybjed already explained, so far, there is no mechanism to really feed configuration requirements from another role to the debops role, as this was done e.g. with Postfix (see e.g. [postfix_dependent_maincf](https://github.com/debops/ansible-postfix/blob/master/defaults/main.yml#L439)

So far I didn't put a lot of effort into offering different Dovecot authentication scenarios, as the one I'm using is implemented and I first wanted to know from people what they need. Setting up authentication via MySQL shouldn't be too much of a problem with the links you gave me. For short term, most of the things should be doable with a custom jinja template (e.g. mailbox setup with a custom *10-mail.conf.j2*).

The only tougher thing that I'm still trying to wind my head around for a nice solution is the plugin configuration. Enabling plugins can be already done with means available, but setting custom configurations to `plugin {}` is still unresolved. Thanks to the guide you mentioned, I now have a good example for a quota configuration, so I might look into this within the coming weeks.

If you have some ideas or patches, just let us know. We'll be happy to have a look at it :-)
