### ISSUE TITLE
postfix dependencies

### ISSUE THREAD

**Issue by le9i0nx** [debops/ansible-dovecot#19]
This dependence prevents use as a transport exim.

**Comment by drybjed** [comment]
Default MTA in DebOps is Postfix, which is managed by `debops.postfix` role. It can be used to easily configure Postfix for several different cases (delivery to a mail hub, local delivery, etc.). In the future, new Ansilble roles in DebOps might provide virtual mail support using Postfix and Dovecot.

If you don't want to use Postfix, try setting:
```
postfix: False
```
in Ansible inventory. That should tell `debops.postfix` to not install and configure Postfix on a host, which should then let you use Exim instead. It might be buggy though, let me know if it works.

`debops.postfix` role will still run because Ansible only supports "hard dependencies" between the roles.

**Comment by le9i0nx** [comment]
This solution is a little something.
I think that the right to do so.
making role for ```debops.dovecot``` and ```debops.postfix```, which will be completely isolated from each other and a third role ```debops.mail_srv``` that contact is necessary components together.

this option will allow more gipko use and mix as well as we would like.

**Comment by drybjed** [comment]
@le9i0nx I'm inclined to try a different solution, described here: https://github.com/debops/debops-playbooks/issues/192

**Comment by drybjed** [comment]
The hard `debops.postfix` dependency was removed from the `debops.dovecot` role. I'm closing this issue as resolved.
