### ISSUE TITLE
Supported encrypted mailboxes

### ISSUE THREAD

**Issue by ypid** [debops/ansible-dovecot#30]
Something like [trees](https://0xacab.org/riseuplabs/trees) could be investigated maybe. The nice thing is that as soon as a new mail arrives, it is encrypted on the server and not laying around in cleartext.

**Comment by drybjed** [comment]
Interesting project. Since the readme speaks about required plaintext passwords, I wonder if the passwords need to be clear in the database, or if the IMAP auth process is passing the password from the user.

Project seems quite new (about 2 months of `git` history) so I don't see it getting into Debian experimental before Debian Stretch is released. Nevertheless, it might be worth keeping an eye on it.

**Comment by drybjed** [comment]
I'm closing this issue for now to not block the migration to the unified `git` repository. The `trees` project will be revisited in the future.
